rc_ulimit: support multiple limits.
Fixes https://github.com/OpenRC/openrc/issues/399#issuecomment-810461921

diff --git a/sh/openrc-run.sh.in b/sh/openrc-run.sh.in
--- a/sh/openrc-run.sh.in
+++ b/sh/openrc-run.sh.in
@@ -39,6 +39,20 @@ sourcex()
 	fi
 }
 
+apply_ulimits()
+{
+	if [ $(( $# % 2 )) -eq 1 ]; then
+		eerror "${RC_SVCNAME}: Invalid RC_ULIMIT setting"
+		return 1
+	fi
+	while [ $# -gt 0 ] ; do
+		if ! ulimit "${1}" "${2}"; then
+			eerror "${RC_SVCNAME}: unable to apply RC_ULIMIT settings"
+		fi
+		shift 2
+	done
+}
+
 sourcex "@LIBEXECDIR@/sh/functions.sh"
 sourcex "@LIBEXECDIR@/sh/rc-functions.sh"
 case $RC_SYS in
@@ -253,12 +267,9 @@ fi
 
 for _cmd; do
 	if [ "$_cmd" != status -a "$_cmd" != describe ]; then
-		# Apply any ulimit defined
-		if [ -n "${rc_ulimit:-$RC_ULIMIT}" ]; then
-			if ! ulimit ${rc_ulimit:-$RC_ULIMIT}; then
-				eerror "${RC_SVCNAME}: unable to apply RC_ULIMIT settings"
-			fi
-		fi
+		# Apply any ulimit(s) defined
+		[ -n "${rc_ulimit:-$RC_ULIMIT}" ] && \
+			apply_ulimits ${rc_ulimit:-$RC_ULIMIT}
 		# Apply cgroups settings if defined
 		if [ "$(command -v cgroup_add_service)" = "cgroup_add_service" ]
 		then
