sh/openrc-run: remove unnecessary loops
openrc-ruh.sh is only ever called from openrc-run.c, with a single
command, so looping over "$@" is unnecessary

diff --git a/sh/openrc-run.sh.in b/sh/openrc-run.sh.in
--- a/sh/openrc-run.sh.in
+++ b/sh/openrc-run.sh.in
@@ -277,31 +277,28 @@ if yesno "${rc_verbose:-$RC_VERBOSE}"; then
 	export EINFO_VERBOSE
 fi
 
-for _cmd; do
-	if [ "$_cmd" != status -a "$_cmd" != describe ]; then
-		# Apply any ulimit(s) defined
-		[ -n "${rc_ulimit:-$RC_ULIMIT}" ] && \
-			apply_ulimits ${rc_ulimit:-$RC_ULIMIT}
-		# Apply cgroups settings if defined
-		if [ "$(command -v cgroup_add_service)" = "cgroup_add_service" ]
+case $1 in
+status|describe) ;;
+*)
+	# Apply any ulimit(s) defined
+	[ -n "${rc_ulimit:-$RC_ULIMIT}" ] && apply_ulimits ${rc_ulimit:-$RC_ULIMIT}
+
+	# Apply cgroups settings if defined
+	if [ "$(command -v cgroup_add_service)" = "cgroup_add_service" ]; then
+		if grep -qs /sys/fs/cgroup /proc/1/mountinfo
 		then
-			if grep -qs /sys/fs/cgroup /proc/1/mountinfo
-			then
-				if [ -d /sys/fs/cgroup -a ! -w /sys/fs/cgroup ]; then
-					eerror "No permission to apply cgroup settings"
-					break
-				fi
+			if [ -d /sys/fs/cgroup -a ! -w /sys/fs/cgroup ]; then
+				eerror "No permission to apply cgroup settings"
+				break
 			fi
-			cgroup_add_service
 		fi
-		[ "$(command -v cgroup_set_limits)" = "cgroup_set_limits" ] &&
-			cgroup_set_limits
-		[ "$(command -v cgroup2_set_limits)" = "cgroup2_set_limits" ] &&
-			[ "$_cmd" = start ] &&
-			cgroup2_set_limits
-		break
+		cgroup_add_service
 	fi
-done
+
+	[ "$(command -v cgroup_set_limits)" = "cgroup_set_limits" ] && cgroup_set_limits
+	[ "$(command -v cgroup2_set_limits)" = "cgroup2_set_limits" ] && cgroup2_set_limits
+	;;
+esac
 
 eval "printf '%s\n' $required_dirs" | while read _d; do
 	if [ -n "$_d" ] && [ ! -d "$_d" ]; then
@@ -327,95 +324,72 @@ if [ -n "$opts" ]; then
 		ewarn "Please use extra_commands, extra_started_commands or extra_stopped_commands."
 fi
 
-while [ -n "$1" ]; do
-	# Special case depend
-	if [ "$1" = depend ]; then
-		shift
+# Special case depend
+if [ "$1" = depend ]; then
+	shift
 
-		# Enter the dir of the init script to fix the globbing
-		# bug 412677
-		cd ${RC_SERVICE%/*}
-		_depend
-		cd /
-		continue
+	# Enter the dir of the init script to fix the globbing
+	# bug 412677
+	cd ${RC_SERVICE%/*}
+	_depend
+	cd /
+
+	return 0
+fi
+
+# See if we have the required function and run it
+for _cmd in describe start stop status ${extra_commands:-$opts} $extra_started_commands $extra_stopped_commands; do
+	[ "$_cmd" = "$1" ] || continue
+	if [ "$(command -v "$1")" != "$1" ]; then
+		case $_cmd in
+			start|stop)
+				exit 0;;
+			*)
+				eerror "$RC_SVCNAME: function '$1' defined but does not exist"
+				exit 1;;
+		esac
+		break
 	fi
-	# See if we have the required function and run it
-	for _cmd in describe start stop status ${extra_commands:-$opts} \
-		$extra_started_commands $extra_stopped_commands
-	do
+done
+
+# If we're in the background, we may wish to fake some commands. We do this so we can
+# "start" ourselves from inactive which then triggers other services to start which
+# depend on us. A good example of this is openvpn.
+if yesno $IN_BACKGROUND; then
+	for _cmd in $in_background_fake; do
 		if [ "$_cmd" = "$1" ]; then
-			if [ "$(command -v "$1")" = "$1" ]; then
-				# If we're in the background, we may wish to
-				# fake some commands. We do this so we can
-				# "start" ourselves from inactive which then
-				# triggers other services to start which
-				# depend on us.
-				# A good example of this is openvpn.
-				if yesno $IN_BACKGROUND; then
-					for _cmd in $in_background_fake; do
-						if [ "$_cmd" = "$1" ]; then
-							shift
-							continue 3
-						fi
-					done
-				fi
-				# Check to see if we need to be started before
-				# we can run this command
-				for _cmd in $extra_started_commands; do
-					if [ "$_cmd" = "$1" ]; then
-						if verify_boot && ! service_started; then
-							eerror "$RC_SVCNAME: cannot \`$1' as it has not been started"
-							exit 1
-						fi
-					fi
-				done
-				# Check to see if we need to be stopped before
-				# we can run this command
-				for _cmd in $extra_stopped_commands; do
-					if [ "$_cmd" = "$1" ]; then
-						if verify_boot && ! service_stopped; then
-							eerror "$RC_SVCNAME: cannot \`$1' as it has not been stopped"
-							exit 1
-						fi
-					fi
-				done
-				unset _cmd
-				case $1 in
-						start|stop|status) verify_boot;;
-				esac
-				if [ "$(command -v "$1_pre")" = "$1_pre" ]
-				then
-					"$1"_pre || exit $?
-				fi
-				"$1" || exit $?
-				if [ "$(command -v "$1_post")" = "$1_post" ]
-				then
-					"$1"_post || exit $?
-				fi
-				[ "$(command -v cgroup_cleanup)" = "cgroup_cleanup" ] &&
-					[ "$1" = "stop" ] &&
-					yesno "${rc_cgroup_cleanup}" && \
-					cgroup_cleanup
-				if [ "$(command -v cgroup2_remove)" = "cgroup2_remove" ]; then
-					[ "$1" = stop ] || [ -z "${command}" ] &&
-					cgroup2_remove
-				fi
-				shift
-				continue 2
-			else
-				if [ "$_cmd" = "start" -o "$_cmd" = "stop" ]
-				then
-					shift
-					continue 2
-				else
-					eerror "$RC_SVCNAME: function \`$1' defined but does not exist"
-					exit 1
-				fi
-			fi
+			exit 0
 		fi
 	done
-	eerror "$RC_SVCNAME: unknown function \`$1'"
-	exit 1
+fi
+
+for _cmd in $extra_started_commands; do
+	[ "$_cmd" = "$1" ] || continue
+	if verify_boot && ! service_started; then
+		eerror "$RC_SVCNAME: cannot '$1' as it has not been started"
+		exit 1
+	fi
 done
+
+for _cmd in $extra_stopped_commands; do
+	[ "$_cmd" = "$1" ] || continue
+	if verify_boot && ! service_stopped; then
+		eerror "$RC_SVCNAME: cannot '$1' as it has not been stopped"
+		exit 1
+	fi
+done
+
+unset _cmd
+
+case $1 in
+	start|stop|status) verify_boot;;
+esac
+
+[ "$(command -v "$1_pre")" = "$1_pre" ] && { "$1"_pre || exit $?; }
+"$1" || exit $?
+[ "$(command -v "$1_post")" = "$1_post" ] && { "$1"_post || exit $?; }
+
+[ "$(command -v cgroup_cleanup)" = cgroup_cleanup ] && [ "$1" = stop ] && yesno "${rc_cgroup_cleanup}" && cgroup_cleanup
+[ "$(command -v cgroup2_remove)" = cgroup2_remove ] && { [ "$1" = stop ] || [ -z "${command}" ]; } && cgroup2_remove
 
 exit 0
