sh/openrc-user.sh: log errors to syslog
users can't really see the stdout of the user.$USER service

diff --git a/sh/openrc-user.sh.in b/sh/openrc-user.sh.in
--- a/sh/openrc-user.sh.in
+++ b/sh/openrc-user.sh.in
@@ -8,7 +8,7 @@ svcdir="${XDG_RUNTIME_DIR?}/openrc"
 
 for config in "@SYSCONFDIR@/rc.conf" "$sysconfdir/rc.conf"; do
 	if [ -e "$config" ] && ! . "$config"; then
-		eerror "openrc-user: Failed loading $config"
+		logger -p daemon.err "openrc-user: Failed loading $config"
 		exit 1
 	fi
 done
@@ -31,5 +31,5 @@ case $1 in
 		cp -pr "$svcdir"/dep* "$svcdir/init.d" "$svcdir/conf.d" "$cachedir" 2>/dev/null
 		exec openrc --user shutdown
 		;;
-	*) eerror "no argument given to $0" && exit 1
+	*) logger -p daemon.err "no argument given to $0" && exit 1
 esac
