sh/openrc-user.sh: log unset XDG_RUNTIME_DIR when failing
avoids confused users seeing the service failing in their logs

diff --git a/sh/openrc-user.sh.in b/sh/openrc-user.sh.in
--- a/sh/openrc-user.sh.in
+++ b/sh/openrc-user.sh.in
@@ -2,6 +2,11 @@
 
 . @LIBEXECDIR@/sh/functions.sh
 
+if [ -z "${XDG_RUNTIME_DIR}" ]; then
+	logger -p daemon.err "XDG_RUNTIME_DIR unset, user services cannot start."
+	exit 1
+fi
+
 sysconfdir="${XDG_CONFIG_HOME:-${HOME}/.config}/rc"
 cachedir="${XDG_CACHE_HOME:-${HOME}/.cache}/rc"
 svcdir="${XDG_RUNTIME_DIR?}/openrc"
