fix tests
X-Gentoo-Bug: 572602
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=572602

diff --git a/scripts/rc-sstat.in b/scripts/rc-sstat.in
--- a/scripts/rc-sstat.in
+++ b/scripts/rc-sstat.in
@@ -52,8 +52,8 @@ if [ ! -d $scandir ]; then
 	exit 1
 fi
 
-# Make sure s6-svscan is running 
-if ! pgrep s6-svscan >/dev/null ; then 
+# Make sure s6-svscan is running
+if ! pgrep s6-svscan >/dev/null ; then
 	printf "s6-svscan is not running\n"
 	exit 1
 fi
@@ -141,7 +141,7 @@ do
 	fi
 done
 
-# Cleanup 
+# Cleanup
 rm -f $statfile 2>/dev/null
 
 printf "\n\n"
