localmount/netmount: clean up critical mount processing
Fix a typo and do not fail if a path in critical_mounts is not listed as
a critical mount does not get mounted.

diff --git a/init.d/netmount.in b/init.d/netmount.in
--- a/init.d/netmount.in
+++ b/init.d/netmount.in
@@ -46,9 +46,13 @@ start()
 		rc=0
 	else
 		for x in ${critical_mounts}; do
-		mountinfo -q $x || critical=x
+		fstabinfo -q $x || continue
+		if ! mountinfo -q $x; then
+			critical=x
+			eerror "Failed to mount $x"
+		fi
 		done
-		[-z "$critical" ] && rc=0
+		[ -z "$critical" ] && rc=0
 	fi
 	return $rc
 }
