savecache: make sure $RC_LIBEXECDIR is writable
This is needed in case of a read-only root filesystem such as a diskless
client.

Reported-by: <walter@pratyeka.org>
X-Gentoo-Bug: 430382
X-Gentoo-Bug-URL: http://bugs.gentoo.org/show_bug.cgi?id=430382

diff --git a/init.d/savecache.in b/init.d/savecache.in
--- a/init.d/savecache.in
+++ b/init.d/savecache.in
@@ -13,6 +13,14 @@ start()
 			return 1
 		fi
 	fi
+	if ! checkpath -W "$RC_LIBEXECDIR"; then
+		ewarn "WARNING: ${RC_LIBEXECDIR} is not writable!"
+		if ! yesno "${RC_GOINGDOWN}"; then
+			ewarn "Unable to save deptree cache"
+			return 1
+		fi
+		return 0
+	fi
 	ebegin "Saving dependency cache"
 	local rc=
 	if [ ! -d "$RC_LIBEXECDIR"/cache ]; then
